language: node_js
node_js:
  - node
  - lts/*

script:
  - npm run lint:all
  - npm run test:all
  - npm run coverage

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run build
        - npm run release